### ISSUE TITLE
BF1 is gone

### ISSUE THREAD

**Issue by HELLSP4RK** [FriendsOfGalaxy/galaxy-integration-origin#1]
Don't have BF1 in GOG Galaxy 2.0 anymore. Tried to reconnect my Origin account, but still can't see it in GOG

**Comment by FriendsOfGalaxy** [comment]
May I ask you to attach either full log located here: c:\ProgramData\GOG.com\Galaxy\logs\plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log
or just the part containing your owned games, something like this: 
```
2019-08-22 14:29:34,990 - root - INFO - Handling request: id=16, method=import_owned_games, params={}
...
2019-08-22 14:29:35,986 - root - DEBUG - Sending 34985 byte of data
2019-08-22 14:29:35,987 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "16", "result": {"owned_games": [{"game_id": "Origin.OFR.50.0002694", "game_title": "Apex Legends\u2122", "license_info": {"license_type": "SinglePurchase"}}]}}
```

**Comment by HELLSP4RK** [comment]
[plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log](https://github.com/FriendsOfGalaxy/galaxy-integration-origin/files/3557018/plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log)

**Comment by FriendsOfGalaxy** [comment]
Could you please check if it's there yet? It might miss some media, but this is something by GOG's side.

**Comment by HELLSP4RK** [comment]
No, it isn't still

**Comment by FriendsOfGalaxy** [comment]
Hey @HELLSP4RK is it fixed for you already? It should, as it works for me.

If Battlefield 1 still do not show up in your library, please write an issue on Galaxy mantis with this information:
```
{"game_id": "Origin.OFR.50.0001384", "game_title": "Battlefield\u2122 1 Deluxe Edition"}
```

**Comment by HELLSP4RK** [comment]
No, it doesn't still. Last time when I report it to Galaxy happen nothing. But thank you!

**Comment by FriendsOfGalaxy** [comment]
No problem.  I'm closing this as it's not the plugin issue.
