### ISSUE TITLE
Change account email causing infinite loop

### ISSUE THREAD

**Issue by codevski** [FriendsOfGalaxy/galaxy-integration-origin#10]
So I ran into this issue where I changed my Origin account email which causes the integration to fall into an infinite loop on connecting..

![connecting](https://media.discordapp.net/attachments/625640414548066315/648674159710306315/unknown.png?width=495&height=57)

I thought maybe deleting the origin installed plugin folder would help but all it does is re-downloads the plugin and starts trying to connect again.

Where can I find the config that stores what plugins I had installed to completely clear the Origin integration to be able to install it as a fresh copy...

At the very least might be a good idea to have a function that times out at X mins then requires you to re enter credentials

**Comment by FriendsOfGalaxy** [comment]
Does this still occur in 0.32 for you ? 
Should auto update after restarting galaxy.

**Comment by codevski** [comment]
> Does this still occur in 0.32 for you ?
> Should auto update after restarting galaxy.

So I am not sure if the update fixed the issue.

Steps I took to sort it out:

- Copy & Deleted Galaxy folder thats located in AppData.

- Launched GOG and noticed all of the plugins started to download and get stuck on connecting.

- Closed GOG and deleted Galaxy folder again and restored the original folder.

- All plugins connected. Origin plugin tried to connect then it switched to Offline.

- This gave me two options to retry or disconnect.

- Disconnected and connected again which allowed me to enter my credentials.

The update prob allowed it to go offline 😄 at least its working fine now and the issue can be closed.

Also keep up the good work 👍
