### ISSUE TITLE
Certain games not showing up in list

### ISSUE THREAD

**Issue by lethesdomoi** [FriendsOfGalaxy/galaxy-integration-origin#13]
I noticed that Sims Medieval Ultimate Edition is not in my list of games. Apparently others have had similar problems:

https://www.gog.com/forum/general_beta_gog_galaxy_2.0/bug_origin_integration_some_games_are_missing/page2

It looks like the plugin may be choking on the word "Edition". I don't know enough about how the API works and don't have time to look into it and offer a solution, but it seems like this one could be an easy fix.

**Comment by FriendsOfGalaxy** [comment]
This may be GOG issue. Please refer to this: https://github.com/FriendsOfGalaxy/galaxy-integration-origin/wiki/Common-problems

**Comment by lethesdomoi** [comment]
Thanks. It is displaying in the logs and I am submitting a bug report to GOG.
