### ISSUE TITLE
No Origin games are showing up in Galaxy 2.0

### ISSUE THREAD

**Issue by PlanetStargazer** [FriendsOfGalaxy/galaxy-integration-origin#14]
For some reason no Origin games show up in Galaxy 2.0. The plugin is connected, I get no error messages, but it doesn't work. Hopefully you can find the issue and fix it, or give me some advice if the problem is on my side.
[plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log](https://github.com/FriendsOfGalaxy/galaxy-integration-origin/files/3977088/plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log)

**Comment by FriendsOfGalaxy** [comment]
Hey, thanks for the report.

Looks like one request for owned game is failing and the whole batch returns an error.
I've prepared test version for you. Please:
1. close Galaxy
2. unpack [plugin.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-origin/files/3979338/plugin.zip) input plugin directory:
```
"%localappdata%\GoG.com\Galaxy\plugins\installed\origin_7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0"
```
(assuming you're on windows)
(file `plugin.py` should be overwriten) 

3. launch Galaxy
4. independently of the result, please attach plugin logs - we will see what game actually causes the problem.

**Comment by PlanetStargazer** [comment]
A lot of games started to appear after using your test version of the plugin.

**Comment by PlanetStargazer** [comment]
[plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log](https://github.com/FriendsOfGalaxy/galaxy-integration-origin/files/3983335/plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log)

**Comment by FriendsOfGalaxy** [comment]
Ok, that's expected :) The problem is with `/mercenaries/mercenaries-world-in-flames/standard-edition` so probably: https://www.origin.com/pol/pl-pl/store/mercenaries/mercenaries-world-in-flames ?

When and where did you buy it?

**Comment by PlanetStargazer** [comment]
I think I know what might have caused the issue. For some reason I have this game twice in my Origin library. I hid one of them. And no, I can not remember where I got those copies. Probably something like a Humble Bundle or it was given away for free at one time.

**Comment by PlanetStargazer** [comment]
Ah, I just found out that the second entry is NOT a second copy of the game but a "Mercenaries Costume Pack Unlock Code". It's basically just a CD key.

**Comment by FriendsOfGalaxy** [comment]
Ok, I see that this game was also properly imported in Galaxy, so this missing thing may be no-longer existing offer that previously was containing this "Costume Pack" along with the game. 

Patch is released, 404s are ignored while fetching game details.
