### ISSUE TITLE
shift 2 unleashed limited edition not picked up by integration

### ISSUE THREAD

**Issue by derailedition** [FriendsOfGalaxy/galaxy-integration-origin#17]
that's about it. let me know if there's more info on this version I can somehow provide, if there's a way to read information through origin or something.

**Comment by FriendsOfGalaxy** [comment]
Hey, thanks for reaching out. Would be awesome if you follow those steps: https://github.com/FriendsOfGalaxy/galaxy-integration-origin/wiki/Common-problems#some-games-are-missing

**Comment by derailedition** [comment]
this part? {"game_id": "DR:224405400", "game_title": "SHIFT 2 UNLEASHED\u2122 Limited Edition", "license_info": {"license_type": "SinglePurchase"}}

**Comment by FriendsOfGalaxy** [comment]
Yes. So it is reported by the plugin. Please send issue to Galaxy via manu->Report Issue.
