### ISSUE TITLE
Incorrect handling of games no longer owned

### ISSUE THREAD

**Issue by pierrebai** [FriendsOfGalaxy/galaxy-integration-origin#19]
**Describe the bug**
When a game ID cannot be found, the plugin causes an unexpected exception instead of detecting it. Here is the traceback from the log file:

2020-05-16 10:01:34,523 - root - ERROR - Game 'DR:110592000' not found amongst owned
Traceback (most recent call last):
  File "C:\Users\Pierre\AppData\Local\GOG.com\Galaxy\plugins\installed\origin_7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0\plugin.py", line 144, in get_unlocked_achievements
    achievements_set = context.owned_games[game_id].achievement_set
KeyError: 'DR:110592000'

**Expected behavior**
You should put a try: except: block around that code (or check game_in in context.owned_game).

**Comment by FriendsOfGalaxy** [comment]
@pierrebai 
Imho there should never be a situation where Galaxy Client asks us for anything for a game which we did not previously report as part of owned games.

Sending a "None" or anything else for that game in this case is putting a blanket on the issue.  Does the exception prevent retrieval of achievements for this game only or for other games as well ?

**Comment by pierrebai** [comment]
It's possible for a game to be no longer owned. For example when the origin subscription ends.

**Comment by FriendsOfGalaxy** [comment]
I understand that it is possible to lose ownership over a game, i am saying that galaxy shouldn't ask for things which weren't reported by the plugin. 

That log snipet you sent clearly indicates that plugin does not have the said game in its cache, so it couldn't have sent it to GOG Galaxy as part of owned games, so Galaxy shouldn't ask for its details.  

Also: `Does the exception prevent retrieval of achievements for this game only or for other games as well ?`
