### ISSUE TITLE
Can't disconnect Origin account

### ISSUE THREAD

**Issue by krugdenis** [FriendsOfGalaxy/galaxy-integration-origin#20]
I can't disconnect my Origin (and Steam also) account to connect a different account. When I hit "Disconnect", a confirmation window opens. After choosing "Confirm" instead of "Cancel" nothing happens. I can repeat this, restart/reinstall GOG Galaxy and the integration as often as I want, nothing changes.

To Reproduce

Log in with account
Decide to use different account
Open integrations settings
Search for Steam (or Origin)
Click "Disconnect" next to Steam (or Origin)
Hit "Confirm" in the confirm window

Expected behavior
After confirming, the connection should be reset and games should be removed from library.

GOGGalaxy Version: 2.0.16.187

**Comment by FriendsOfGalaxy** [comment]
Hi, probably Galaxy backend issue. Please report to Galaxy bug-tracker by going to cog-wheel menu -> ReportIssue if it still occurs.
