### ISSUE TITLE
origin not showing up ultimate editions or deluxe editions

### ISSUE THREAD

**Issue by gloomcookie666** [FriendsOfGalaxy/galaxy-integration-origin#25]
**Before start**
- check if your issue is known: https://github.com/FriendsOfGalaxy/galaxy-integration-origin/wiki/Common-problems

**Describe the bug**
Generally games show up fine with the origin plugin, however if a title owned is the deluxe edition or ultimate edition of a game it dows not show up in thw owned list. For instance I own the deluxe edition of Battlefield 1, which does not show up on the origin tab at all.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Log in with account that has any deluxe edition or ultimate edition origin titles
3. Check the origin tab to see the game not there

**Expected behavior**
All games except for those that are deluxe edition or ultimate edition to be present

**Comment by FriendsOfGalaxy** [comment]
Hi @gloomcookie666, thanks for reporting this. I'm not sure that game edition is a root problem here.
can you attach logs?
https://github.com/FriendsOfGalaxy/galaxy-integration-origin/wiki/Log-files

**Comment by gloomcookie666** [comment]
absolutely, this is my latest origin log. hopefully ive uploaded it right
[plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log](https://github.com/FriendsOfGalaxy/galaxy-integration-origin/files/5509933/plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log)

**Comment by FriendsOfGalaxy** [comment]
thanks, @gloomcookie666 
I can see in logs that ultimate version of games are send by plugin, so that is GOG database problem.

```
{
      "game_id": "Origin.OFR.50.0001382",
      "game_title": "Battlefield™ 1 Deluxe Edition",
      "license_info": {
        "license_type": "SinglePurchase"
      }
 }
```

You didn't followed `Before start` section :(
