### ISSUE TITLE
Origin games bought from Epic Games store not launching

### ISSUE THREAD

**Issue by claushofmann** [FriendsOfGalaxy/galaxy-integration-origin#29]
**Describe the bug**
When buying an EA game (such as Star Wars Battlefront 2) from the Epic Games store and installing it, the game is recognized by the Galaxy Origin integration as installed on Origin. When trying to launch the game via Galaxy, Origin shows an error message saying that the game needs to be activated and does not launch the game.

**To Reproduce**
1. Install an EA game from the Epic Game Store
2. Try to launch it via the Galaxy Origin integration

**Expected behavior**
The game should launch correctly

**Attached logs**
[plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log](https://github.com/FriendsOfGalaxy/galaxy-integration-origin/files/5887695/plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log)

**Error message**
![origin_error](https://user-images.githubusercontent.com/23155858/106138447-70b1e100-616c-11eb-83ca-4fadcba69de0.PNG)

**Comment by FriendsOfGalaxy** [comment]
BTW: Origin has the similar bug when you try to launch game from their webpage via "Play on Origin".

They give empty string to `externalType` like:
`origin2://game/launch?offerIds=Origin.OFR.50.0002522&autoDownload=1&externalType=`

**Comment by claushofmann** [comment]
Seems like we're way ahead on this issue than Origin themselves :P
I can reproduce the issue when I try to start the game from the landing page. If I start it from "My Game Library" the game launches correctly.

**Comment by FriendsOfGalaxy** [comment]
Should work in 0.39, @claushofmann could you check?

**Comment by claushofmann** [comment]
Hi, yes, can confirm. My copy of Battlefront 2 bought from the Epic Store is now launching via the Origin Galaxy integration
