### ISSUE TITLE
Sims 4 no properly detected

### ISSUE THREAD

**Issue by EowynCarter** [FriendsOfGalaxy/galaxy-integration-origin#3]
I own the sims 4 (limited edition) but galaxy shows only the create a sim demo.

**Comment by FriendsOfGalaxy** [comment]
Can you check now?

**Comment by EowynCarter** [comment]
Perfect. It works now :) Tanks you so much.

**Comment by EowynCarter** [comment]
Ok, there these to be an other (less problematic), issue.

it show : f
first played : 12 days ago (wrong)
reached 150 hours 12 days ago (wrong)
reach 25 hours : 5 years ago (seams legit)
played for the first time : 5 year ago (legit)

total play time : 232 hours (legit too)

12 days ago, there was the update. probably what messed up the stats.  Battlefront II say "play for the first time : 2 months ago (should be one year). So it seam it's not a sims 4 related issue.

**Comment by FriendsOfGalaxy** [comment]
I'm closing this, as original issue was solved. If you still encounter any problems with gametimes, please create new issue. Thanks!
