### ISSUE TITLE
Achievements no longer appear

### ISSUE THREAD

**Issue by zer0no0** [FriendsOfGalaxy/galaxy-integration-origin#33]
Achievements no longer appear on any origin linked game, even the ones that used to be there have disappeared, basically all origin linked games now behave like they don't support achievements, for example in the 'my progress' tab, under achievements it says n/a, otherwise it tracks and imports other data like 'game time' normally.

Tried disconnecting quitting the application then reconnecting, syncing integrations, removing and reinstalling the integration itself, and removing the storage.db file. 

Last two log files attached:
[plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log](https://github.com/FriendsOfGalaxy/galaxy-integration-origin/files/6588912/plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log)

[plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log](https://github.com/FriendsOfGalaxy/galaxy-integration-origin/files/6588909/plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log)

Thank you

**Comment by FriendsOfGalaxy** [comment]
@zer0no0 has it fixed itself for you?
