### ISSUE TITLE
EA Play Showing wrong A Way Out

### ISSUE THREAD

**Issue by ciaron88** [FriendsOfGalaxy/galaxy-integration-origin#35]
**Describe the bug**
EA Play Subscription links to the wrong A Way Out game. it Shows a VR "Way Out" game - https://store.steampowered.com/app/791380/Way_Out/ should be A Way Out https://www.origin.com/gbr/en-us/store/a-way-out/a-way-out

![image](https://user-images.githubusercontent.com/31342057/128515619-1384f706-57bf-4976-9331-2bcaa60970a1.png)

**Expected behavior**
Should link to the game A Way Out https://www.origin.com/gbr/en-us/store/a-way-out/a-way-out

**Comment by fl4shback** [comment]
Can confirm, the "imported" steam version does the same thing

**Comment by ciaron88** [comment]
Just opened GOG. looks like it has been fixed for me :)
