### ISSUE TITLE
Games in Origin are always listed as "Recent"

### ISSUE THREAD

**Issue by quanah** [FriendsOfGalaxy/galaxy-integration-origin#38]
When I look at the "Recent" tab in GoG, every game in my Origin library is listed as being "recent", despite the fact that I've not purchased a game from Origin in a few years.

**To Reproduce**
1. Connect GoG with Origin
2. Look at "Recent" section

**Expected behavior**
Only recently purchased games are shown

**Comment by UncleGoogle** [comment]
Recent tab shows newly added games, not newly bought, so I guess it is as expected

**Comment by ShaunV2** [comment]
That is working as it should be, that is for all recently added games of any type.

**Comment by quanah** [comment]
You've misunderstood.  I've added ZERO games to origin.  I haven't had any different games in Origin for *years*.  But the plugin always says they are "recent".  Apparently this was fixed recently, since it no longer happens.
