### ISSUE TITLE
PVZ Garden Warfare 1 not appear

### ISSUE THREAD

**Issue by RaptorPharaoh** [FriendsOfGalaxy/galaxy-integration-origin#4]
Nothing to add, only the tittle. Thanks

**Comment by RaptorPharaoh** [comment]
Hello, in my Origin plugin not appear my Plants VS Zombies: Garden Warfare 1 because I have the Digital Deluxe Edition and this version isn't appear in GOG's search engine, only appears the Standard Edition [GW2 have both editions listed]. Please can you ask them for add the entry to the GOG's database? Thanks

**Comment by FriendsOfGalaxy** [comment]
Sure. I'm sending report. For the future you can send it by yourself:
- check in plugin log file `%programdata%\GOG.com\Galaxy\logs` if there is this title
- if not - report here - else: this game is properly send from plugin but spammed/hidden in Galaxy
- get id of this title from log
- send report using galaxy cogwheel menu -> Report issue

**Comment by RaptorPharaoh** [comment]
Hi, thank you so much :) and ok I'll follow the instructions you told me.

**Comment by FriendsOfGalaxy** [comment]
@RaptorPharaoh I'm closing for now, but let us now it it was fixed or not within few weeks.
