### ISSUE TITLE
Origin python background process still running when GOG Beta closed.

### ISSUE THREAD

**Issue by benten2000** [FriendsOfGalaxy/galaxy-integration-origin#5]
I reported this to GOG support as well as here now.

Got my GOG Beta invite and installed the latest version 2.0.5.138 and added the plugins support for my other accounts (Steam, Uplay, Origin) which worked fine.

But when I fully close down GOG there are processes still running that never do unless forced:
GOG Galaxy (32 bit) (2)
----Python (32 Bit)
----Console Window Host

Checked what both these processes are linking to (command line) (as requested from GOG support):

**Python**
"C:\Program Files (x86)\GOG Galaxy\python\python.exe" "C:\Program Files (x86)\GOG Galaxy\plugin_runner.py" C:\Users\Administrator\AppData\Local\GOG.com\Galaxy\plugins\installed\origin_7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0\plugin.py 21e8cc57-0e00-4877-8683-66efb47baded 50718 C:\ProgramData\GOG.com\Galaxy\logs\plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log

**Console Window Host**
\??\C:\Windows\system32\conhost.exe 0x4

Tried a reinstall of the community integrations (only Origin when you press disconnect) always stops and reports **Plugin has crashed. Retry.** as well as deleted all of the Origin plugin and db file and installed manually the one from Github (v0.28) will the still the same problem.

[plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log](https://github.com/FriendsOfGalaxy/galaxy-integration-origin/files/3632566/plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log)

**Comment by FriendsOfGalaxy** [comment]
This should be fixed by now. Thx for reporting it!
