### ISSUE TITLE
Missing game : Dragon Age Origins Digital Deluxe edition

### ISSUE THREAD

**Issue by Choum28** [FriendsOfGalaxy/galaxy-integration-origin#8]
Hello,

As said in title, this specific game version is not detected by the plugin.

But in log the game seems found :
{"game_id": "DR:151951600", "game_title": "Dragon Age:\u2122 Origins Digital Deluxe Edition", "license_info": {"license_type": "SinglePurchase"}}

**Comment by FriendsOfGalaxy** [comment]
If a game appears in log, then it is Galaxy gamesDb issue. Please report by cogwheel->Report Issue
From experience the fix may lasts up to few weeks.
