### ISSUE TITLE
STAR WARS Jedi: Fallen Order achievements not showing up in Galaxy 2.0

### ISSUE THREAD

**Issue by Deepo** [FriendsOfGalaxy/galaxy-integration-origin#9]
Achievements for STAR WARS Jedi: Fallen Order are not showing up in Galaxy 2.0. 
![image](https://user-images.githubusercontent.com/2171572/69484318-25969280-0e32-11ea-9d6d-ce891689ef48.png)

**Comment by FriendsOfGalaxy** [comment]
Thanks for report. So this game support achievements, right? Can you attach you origin log file from
`C:\ProgramData\GOG.com\Galaxy\logs` please? (assuming standard location on Windows)

**Comment by Deepo** [comment]
Thank you for looking into it. The game does indeed have achievements, and I see that my achievements actually appears in the log file, but they don't show up in the Galaxy client.

 [plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log](https://github.com/FriendsOfGalaxy/galaxy-integration-origin/files/3888870/plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log)

**Comment by FriendsOfGalaxy** [comment]
Hi, so its probably similar problem to this one:
https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/17

**Comment by Deepo** [comment]
Sounds like that could be the same problem. I had the game pre-ordered.

**Comment by lionnesquaer** [comment]
I have same problem

**Comment by Deepo** [comment]
Seems to be fixed now, all my Origin games, including ones I pre-ordered, are now showing with achievements in Galaxy 2.0
